apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: investigation-team
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: investigation_team
  ConnectionStrings__DefaultConnection: "Host=postgres-svc;Port=5432;Database=investigation_team;Username=postgres;Password=postgres"
