apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: terraria-agent-data-pvc
  namespace: terraria
  labels:
    app: terraria-agent
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
