apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: terraria-world-pvc
  namespace: terraria
  labels:
    app: terraria-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
