apiVersion: v1
kind: Service
metadata:
  name: terraria-server
  namespace: terraria
  labels:
    app: terraria-server
spec:
  type: LoadBalancer
  ports:
    - port: 7777
      targetPort: 7777
      protocol: TCP
      name: game
  selector:
    app: terraria-server
