apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: terraria-server
  namespace: terraria
  labels:
    app: terraria-server
spec:
  serviceName: terraria-server
  replicas: 1
  selector:
    matchLabels:
      app: terraria-server
  template:
    metadata:
      labels:
        app: terraria-server
    spec:
      containers:
        - name: terraria
          image: docker.io/library/terraria-tshock-1455:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 7777
              name: game
              protocol: TCP
            - containerPort: 7878
              name: restapi
              protocol: TCP
            - containerPort: 7879
              name: plugin-cmd
              protocol: TCP
          env:
            - name: WORLD_NAME
              value: "MundoSobrinos2"
            - name: WORLD_SIZE
              value: "3"
            - name: DIFFICULTY
              value: "2"
            - name: MAX_PLAYERS
              value: "8"
            - name: PORT
              value: "7777"
            - name: AUTOCREATE
              value: "1"
            - name: CONFIGPATH
              value: "/config"
            - name: LOGPATH
              value: "/tshock/logs"
            - name: REST_TOKEN
              value: "terraria-agent-secret-token-2024"
            - name: AGENT_URL
              value: "http://terraria-agent:8080"
          volumeMounts:
            - name: terraria-world
              mountPath: /root/.local/share/Terraria/Worlds
            - name: terraria-config
              mountPath: /config
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          readinessProbe:
            tcpSocket:
              port: 7777
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 7777
            initialDelaySeconds: 1800
            periodSeconds: 30
      volumes:
        - name: terraria-world
          persistentVolumeClaim:
            claimName: terraria-world-pvc
        - name: terraria-config
          emptyDir: {}
