apiVersion: v1
kind: Service
metadata:
  name: supermarket-frontend
  namespace: supermarket
  labels:
    app: supermarket-frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: supermarket-frontend
