apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-chat-pvc
  namespace: investigation-team-frontend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
