apiVersion: v1
kind: Service
metadata:
  name: investigation-team-frontend-svc
  namespace: investigation-team-frontend
spec:
  type: LoadBalancer
  selector:
    app: investigation-team-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081