apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: supermarket-postgres-pvc
  namespace: supermarket
  labels:
    app: supermarket-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
