apiVersion: v1
kind: Secret
metadata:
  name: supermarket-postgres-secret
  namespace: supermarket
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: supermarket
